case 'account':
  return postaccount(request);
case 'workflowtargetfilters':
  return postworkflowTargetFilters(request);
case 'theme':
  return posttheme(request);
case 'prismamigrations':
  return postprismaMigrations(request);
case 'eventcategory':
  return posteventCategory(request);
case 'persons':
  return postpersons(request);
case 'contactcustomfieldsection':
  return postcontactCustomFieldSection(request);
case 'loleadsource':
  return postloLeadSource(request);
case 'events':
  return postevents(request);
case 'engagement':
  return postengagement(request);
case 'contactstatuslifecycle':
  return postcontactStatusLifecycle(request);
case 'contacttag':
  return postcontactTag(request);
case 'eventtype':
  return posteventType(request);
case 'templateversion':
  return posttemplateVersion(request);
case 'elementversion':
  return postelementVersion(request);
case 'stripesubscriptionitem':
  return poststripeSubscriptionItem(request);
case 'pageversion':
  return postpageVersion(request);
case 'property':
  return postproperty(request);
case 'eventsv2':
  return posteventsV2(request);
case 'contactcustomfield':
  return postcontactCustomField(request);
case 'contactstatus':
  return postcontactStatus(request);
case 'template':
  return posttemplate(request);
case 'element':
  return postelement(request);
case 'contactfilter':
  return postcontactFilter(request);
case 'filterpermission':
  return postfilterPermission(request);
case 'bridgesectionlifecycle':
  return postbridgeSectionLifecycle(request);
case 'losubscription':
  return postloSubscription(request);
case 'losubscriptiondailystats':
  return postloSubscriptionDailyStats(request);
case 'page':
  return postpage(request);
case 'elementtotemplateversion':
  return postelementtotemplateVersion(request);
case 'templatedependency':
  return posttemplateDependency(request);
case 'routing':
  return postrouting(request);
case 'user':
  return postuser(request);
case 'organization':
  return postorganization(request);
case 'loleadraw':
  return postloLeadRaw(request);
case 'partner':
  return postpartner(request);
case 'workflow':
  return postworkflow(request);
case 'workflowtemplate':
  return postworkflowTemplate(request);
case 'workflowtoworkflowtargetfilters':
  return postworkflowtoworkflowTargetFilters(request);
case 'lolead':
  return postloLead(request);
case 'links':
  return postlinks(request);
case 'workflowstate':
  return postworkflowState(request);
case 'loan':
  return postloan(request);
case 'workflowtemplatepermission':
  return postworkflowTemplatePermission(request);
case 'contact':
  return postcontact(request);
case 'contactpermission':
  return postcontactPermission(request);
case 'incomesource':
  return postincomeSource(request);
case 'contactcomment':
  return postcontactComment(request);
case 'bridgecontactuser':
  return postbridgeContactUser(request);
case 'bridgecontacttag':
  return postbridgeContactTag(request);
case 'contactreminder':
  return postcontactReminder(request);
case 'bridgecontactpartner':
  return postbridgeContactPartner(request);
case 'contactotherassociates':
  return postcontactOtherAssociates(request);
case 'bridgecontactloan':
  return postbridgeContactLoan(request);
case 'activitylog':
  return postactivityLog(request);
case 'bridgecontactprimaryincome':
  return postbridgeContactPrimaryIncome(request);
case 'contactcustomfieldvalue':
  return postcontactCustomFieldValue(request);
case 'bridgecontactcontact':
  return postbridgeContactContact(request);
