import ajvInstance from '../ajv-instance';
import { eventsV2_ajv } from '../mapper_ajv';


const eventsV2_schema = {
  type: 'object',
  properties: {
    eventCategoryId: eventsV2_ajv.eventCategoryId.api,
    eventCategory: eventsV2_ajv.eventCategory.api,
    eventTypeId: eventsV2_ajv.eventTypeId.api,
    eventType: eventsV2_ajv.eventType.api,
    eventData: eventsV2_ajv.eventData.api,
    eventProvider: eventsV2_ajv.eventProvider.api,
    rawBucket: eventsV2_ajv.rawBucket.api,
    rawPath: eventsV2_ajv.rawPath.api,
    reason: eventsV2_ajv.reason.api,
    destinationLocation: eventsV2_ajv.destinationLocation.api,
    destinationType: eventsV2_ajv.destinationType.api,
    deviceIp: eventsV2_ajv.deviceIp.api,
    deviceLocationCity: eventsV2_ajv.deviceLocationCity.api,
    deviceLocationContinent: eventsV2_ajv.deviceLocationContinent.api,
    deviceLocationCoordinatesLat: eventsV2_ajv.deviceLocationCoordinatesLat.api,
    deviceLocationCoordinatesLon: eventsV2_ajv.deviceLocationCoordinatesLon.api,
    deviceLocationCountry: eventsV2_ajv.deviceLocationCountry.api,
    deviceLocationZip: eventsV2_ajv.deviceLocationZip.api,
    deviceTimezone: eventsV2_ajv.deviceTimezone.api,
    deviceType: eventsV2_ajv.deviceType.api,
    userPool: eventsV2_ajv.userPool.api,
    destinationId: eventsV2_ajv.destinationId.api,
    endTime: eventsV2_ajv.endTime.api,
    eventClass: eventsV2_ajv.eventClass.api,
    eventCode: eventsV2_ajv.eventCode.api,
    eventSeverity: eventsV2_ajv.eventSeverity.api,
    eventTime: eventsV2_ajv.eventTime.api,
    message: eventsV2_ajv.message.api,
    ownerId: eventsV2_ajv.ownerId.api,
    referralId: eventsV2_ajv.referralId.api,
    referralType: eventsV2_ajv.referralType.api,
    startTime: eventsV2_ajv.startTime.api,
    resourceId: eventsV2_ajv.resourceId.api,
    resourceType: eventsV2_ajv.resourceType.api,
    sourceId: eventsV2_ajv.sourceId.api,
    sourceType: eventsV2_ajv.sourceType.api,
    timeZone: eventsV2_ajv.timeZone.api,
    channelId: eventsV2_ajv.channelId.api,
    channelType: eventsV2_ajv.channelType.api,
  },
  required: ['eventTime', 'eventData'],
  additionalProperties: false,
};

export default ajvInstance.compile(eventsV2_schema);
