import ajvInstance from '../ajv-instance';
import { loLead_ajv } from '../mapper_ajv';


const loLead_schema = {
  type: 'object',
  properties: {
    assignmentId: loLead_ajv.assignmentId.api,
    billed: loLead_ajv.billed.api,
    boberdooId: loLead_ajv.boberdooId.api,
    callCenterService: loLead_ajv.callCenterService.api,
    companyId: loLead_ajv.companyId.api,
    creditStatus: loLead_ajv.creditStatus.api,
    email: loLead_ajv.email.api,
    firstName: loLead_ajv.firstName.api,
    language: loLead_ajv.language.api,
    lastName: loLead_ajv.lastName.api,
    ownerId: loLead_ajv.ownerId.api,
    phone: loLead_ajv.phone.api,
    productId: loLead_ajv.productId.api,
    provider: loLead_ajv.provider.api,
    vendor: loLead_ajv.vendor.api,
    secondaryPhone: loLead_ajv.secondaryPhone.api,
    source: loLead_ajv.source.api,
    subscriptionId: loLead_ajv.subscriptionId.api,
    price: loLead_ajv.price.api,
    transferPrice: loLead_ajv.transferPrice.api,
    transferStatus: loLead_ajv.transferStatus.api,
    leadType: loLead_ajv.leadType.api,
    leadCategory: loLead_ajv.leadCategory.api,
    addressCity: loLead_ajv.addressCity.api,
    addressCountry: loLead_ajv.addressCountry.api,
    addressState: loLead_ajv.addressState.api,
    addressStreet: loLead_ajv.addressStreet.api,
    addressStreet2: loLead_ajv.addressStreet2.api,
    addressStreet3: loLead_ajv.addressStreet3.api,
    addressZip: loLead_ajv.addressZip.api,
    loanDownPayment: loLead_ajv.loanDownPayment.api,
    loanInterestRate: loLead_ajv.loanInterestRate.api,
    loanMonthlyPayment: loLead_ajv.loanMonthlyPayment.api,
    loanPurchasePrice: loLead_ajv.loanPurchasePrice.api,
    loanTransactionType: loLead_ajv.loanTransactionType.api,
    loanType: loLead_ajv.loanType.api,
    loLeadRawId: loLead_ajv.loLeadRawId.api,
    loanRange: loLead_ajv.loanRange.api,
    creditedPrice: loLead_ajv.creditedPrice.api,
    creditedTransferPrice: loLead_ajv.creditedTransferPrice.api,
    refundedPrice: loLead_ajv.refundedPrice.api,
    refundedTransferPrice: loLead_ajv.refundedTransferPrice.api,
    transferDate: loLead_ajv.transferDate.api,
  },
  required: ['price', 'refundedTransferPrice', 'creditedTransferPrice', 'subscriptionId', 'transferPrice', 'billed', 'creditedPrice', 'refundedPrice'],
  additionalProperties: false,
};

export default ajvInstance.compile(loLead_schema);
