import ajvInstance from '../ajv-instance';
import { loSubscription_ajv } from '../mapper_ajv';


const loSubscription_schema = {
  type: 'object',
  properties: {
    id: loSubscription_ajv.id.api,
    stripeStatus: loSubscription_ajv.stripeStatus.api,
    stripePaymentIntent: loSubscription_ajv.stripePaymentIntent.api,
    boberdooId: loSubscription_ajv.boberdooId.api,
    boberdooBalance: loSubscription_ajv.boberdooBalance.api,
    cancelTime: loSubscription_ajv.cancelTime.api,
    companyId: loSubscription_ajv.companyId.api,
    createRequest: loSubscription_ajv.createRequest.api,
    currentStep: loSubscription_ajv.currentStep.api,
    deactivateTime: loSubscription_ajv.deactivateTime.api,
    finishTime: loSubscription_ajv.finishTime.api,
    inactive: loSubscription_ajv.inactive.api,
    price: loSubscription_ajv.price.api,
    priceSubscriptionItemId: loSubscription_ajv.priceSubscriptionItemId.api,
    transferPrice: loSubscription_ajv.transferPrice.api,
    transferPriceSubscriptionItemId: loSubscription_ajv.transferPriceSubscriptionItemId.api,
    updatedBy: loSubscription_ajv.updatedBy.api,
    updateTime: loSubscription_ajv.updateTime.api,
    callCenterService: loSubscription_ajv.callCenterService.api,
    scheduleDays: loSubscription_ajv.scheduleDays.api,
    scheduleTo: loSubscription_ajv.scheduleTo.api,
    timeZone: loSubscription_ajv.timeZone.api,
    primaryPhone: loSubscription_ajv.primaryPhone.api,
    primaryPhoneVerified: loSubscription_ajv.primaryPhoneVerified.api,
    secondaryPhone: loSubscription_ajv.secondaryPhone.api,
    secondaryPhoneVerified: loSubscription_ajv.secondaryPhoneVerified.api,
    addressCity: loSubscription_ajv.addressCity.api,
    addressCountry: loSubscription_ajv.addressCountry.api,
    addressStreet: loSubscription_ajv.addressStreet.api,
    addressStreet3: loSubscription_ajv.addressStreet3.api,
    stripeSubscription: loSubscription_ajv.stripeSubscription.api,
    primaryPhoneType: loSubscription_ajv.primaryPhoneType.api,
    autoBilling: loSubscription_ajv.autoBilling.api,
    createTime: loSubscription_ajv.createTime.api,
    createdBy: loSubscription_ajv.createdBy.api,
    productId: loSubscription_ajv.productId.api,
    dailyBudgetLimit: loSubscription_ajv.dailyBudgetLimit.api,
    leadCategory: loSubscription_ajv.leadCategory.api,
    addressState: loSubscription_ajv.addressState.api,
    creditStatus: loSubscription_ajv.creditStatus.api,
    updateRequest: loSubscription_ajv.updateRequest.api,
    deactivateReason: loSubscription_ajv.deactivateReason.api,
    activeLeadTransfer: loSubscription_ajv.activeLeadTransfer.api,
    bundleTitle: loSubscription_ajv.bundleTitle.api,
    scheduleFrom: loSubscription_ajv.scheduleFrom.api,
    totalCredited: loSubscription_ajv.totalCredited.api,
    totalLeadsMatched: loSubscription_ajv.totalLeadsMatched.api,
    preferredmeetingplaceStreet3: loSubscription_ajv.preferredmeetingplaceStreet3.api,
    totalMatchAmount: loSubscription_ajv.totalMatchAmount.api,
    infoEmail: loSubscription_ajv.infoEmail.api,
    preferredcommunicationscheduleFrom: loSubscription_ajv.preferredcommunicationscheduleFrom.api,
    addressZip: loSubscription_ajv.addressZip.api,
    preferredmeetingplaceCountry: loSubscription_ajv.preferredmeetingplaceCountry.api,
    secondaryPhoneType: loSubscription_ajv.secondaryPhoneType.api,
    loanType: loSubscription_ajv.loanType.api,
    county: loSubscription_ajv.county.api,
    dailyUnitLimit: loSubscription_ajv.dailyUnitLimit.api,
    infoWebsite: loSubscription_ajv.infoWebsite.api,
    transactionType: loSubscription_ajv.transactionType.api,
    infoPhone: loSubscription_ajv.infoPhone.api,
    agentState: loSubscription_ajv.agentState.api,
    addressStreet2: loSubscription_ajv.addressStreet2.api,
    preferredmeetingplaceStreet: loSubscription_ajv.preferredmeetingplaceStreet.api,
  },
  required: [],
  additionalProperties: false,
};

export default ajvInstance.compile(loSubscription_schema);
