import ajvInstance from '../ajv-instance';
import { loSubscription_ajv } from '../mapper_ajv';


const loSubscription_schema = {
  type: 'object',
  properties: {
    stripeStatus: loSubscription_ajv.stripeStatus.api,
    autoBilling: loSubscription_ajv.autoBilling.api,
    boberdooBalance: loSubscription_ajv.boberdooBalance.api,
    cancelTime: loSubscription_ajv.cancelTime.api,
    dailyBudgetLimit: loSubscription_ajv.dailyBudgetLimit.api,
    deactivateTime: loSubscription_ajv.deactivateTime.api,
    price: loSubscription_ajv.price.api,
    transferPrice: loSubscription_ajv.transferPrice.api,
    activeLeadTransfer: loSubscription_ajv.activeLeadTransfer.api,
    secondaryPhoneType: loSubscription_ajv.secondaryPhoneType.api,
    addressCity: loSubscription_ajv.addressCity.api,
    addressState: loSubscription_ajv.addressState.api,
    addressStreet2: loSubscription_ajv.addressStreet2.api,
    preferredmeetingplaceStreet3: loSubscription_ajv.preferredmeetingplaceStreet3.api,
    preferredmeetingplaceCountry: loSubscription_ajv.preferredmeetingplaceCountry.api,
    primaryPhone: loSubscription_ajv.primaryPhone.api,
    preferredmeetingplaceStreet: loSubscription_ajv.preferredmeetingplaceStreet.api,
    vendors: loSubscription_ajv.vendors.api,
    creditStatus: loSubscription_ajv.creditStatus.api,
    infoName: loSubscription_ajv.infoName.api,
    currentStep: loSubscription_ajv.currentStep.api,
    weight: loSubscription_ajv.weight.api,
    scheduleFrom: loSubscription_ajv.scheduleFrom.api,
    totalRefunded: loSubscription_ajv.totalRefunded.api,
    infoEmail: loSubscription_ajv.infoEmail.api,
    stripeSubscription: loSubscription_ajv.stripeSubscription.api,
    preferredcommunicationscheduleFrom: loSubscription_ajv.preferredcommunicationscheduleFrom.api,
    totalTransferAmount: loSubscription_ajv.totalTransferAmount.api,
    finishTime: loSubscription_ajv.finishTime.api,
    agentState: loSubscription_ajv.agentState.api,
    county: loSubscription_ajv.county.api,
    priceSubscriptionItemId: loSubscription_ajv.priceSubscriptionItemId.api,
    totalLeadsTransfered: loSubscription_ajv.totalLeadsTransfered.api,
    secondaryPhoneVerified: loSubscription_ajv.secondaryPhoneVerified.api,
    timeZone: loSubscription_ajv.timeZone.api,
    primaryPhoneType: loSubscription_ajv.primaryPhoneType.api,
    loanRanges: loSubscription_ajv.loanRanges.api,
    boberdooId: loSubscription_ajv.boberdooId.api,
    bundleTitle: loSubscription_ajv.bundleTitle.api,
    callCenterService: loSubscription_ajv.callCenterService.api,
    deactivateReason: loSubscription_ajv.deactivateReason.api,
    productId: loSubscription_ajv.productId.api,
    scheduleTo: loSubscription_ajv.scheduleTo.api,
    alertList: loSubscription_ajv.alertList.api,
    leadType: loSubscription_ajv.leadType.api,
    dailyUnitLimit: loSubscription_ajv.dailyUnitLimit.api,
    transferPriceSubscriptionItemId: loSubscription_ajv.transferPriceSubscriptionItemId.api,
    inactive: loSubscription_ajv.inactive.api,
    scheduleDays: loSubscription_ajv.scheduleDays.api,
    stripePaymentIntent: loSubscription_ajv.stripePaymentIntent.api,
    companyId: loSubscription_ajv.companyId.api,
    secondaryPhone: loSubscription_ajv.secondaryPhone.api,
    addressZip: loSubscription_ajv.addressZip.api,
    userId: loSubscription_ajv.userId.api,
  },
  required: ['loanRanges', 'weight'],
  additionalProperties: false,
};

export default ajvInstance.compile(loSubscription_schema);
