import ajvInstance from '../ajv-instance';
import { events_ajv } from '../mapper_ajv';


const events_schema = {
  type: 'object',
  properties: {
    eventAction: events_ajv.eventAction.api,
    eventCategory: events_ajv.eventCategory.api,
    eventClass: events_ajv.eventClass.api,
    eventCode: events_ajv.eventCode.api,
    eventData: events_ajv.eventData.api,
    eventGroup: events_ajv.eventGroup.api,
    eventId: events_ajv.eventId.api,
    eventName: events_ajv.eventName.api,
    eventProvider: events_ajv.eventProvider.api,
    eventSeverity: events_ajv.eventSeverity.api,
    eventType: events_ajv.eventType.api,
    message: events_ajv.message.api,
    outcome: events_ajv.outcome.api,
    parentId: events_ajv.parentId.api,
    rawPath: events_ajv.rawPath.api,
    reason: events_ajv.reason.api,
    createTime: events_ajv.createTime.api,
    endTime: events_ajv.endTime.api,
    eventTime: events_ajv.eventTime.api,
    startTime: events_ajv.startTime.api,
    destinationId: events_ajv.destinationId.api,
    channelId: events_ajv.channelId.api,
    channelType: events_ajv.channelType.api,
    destinationLocation: events_ajv.destinationLocation.api,
    destinationType: events_ajv.destinationType.api,
    deviceIp: events_ajv.deviceIp.api,
    deviceLocationCity: events_ajv.deviceLocationCity.api,
    deviceLocationContinent: events_ajv.deviceLocationContinent.api,
    deviceLocationCoordinatesLat: events_ajv.deviceLocationCoordinatesLat.api,
    deviceLocationCoordinatesLon: events_ajv.deviceLocationCoordinatesLon.api,
    deviceLocationCountry: events_ajv.deviceLocationCountry.api,
    deviceLocationZip: events_ajv.deviceLocationZip.api,
    deviceTimezone: events_ajv.deviceTimezone.api,
    deviceType: events_ajv.deviceType.api,
    referralId: events_ajv.referralId.api,
    referralType: events_ajv.referralType.api,
    resourceId: events_ajv.resourceId.api,
    resourceType: events_ajv.resourceType.api,
    sourceId: events_ajv.sourceId.api,
    sourceType: events_ajv.sourceType.api,
    userAgent: events_ajv.userAgent.api,
    userPool: events_ajv.userPool.api,
    timezone: events_ajv.timezone.api,
  },
  required: ,
  additionalProperties: false,
};

export default ajvInstance.compile(events_schema);
