import ajvInstance from '../ajv-instance';
import { loSubscription_ajv } from '../mapper_ajv';


const loSubscription_schema = {
  type: 'object',
  properties: {
    id: loSubscription_ajv.id.api,
    stripeSubscription: loSubscription_ajv.stripeSubscription.api,
    stripeStatus: loSubscription_ajv.stripeStatus.api,
    stripePaymentIntent: loSubscription_ajv.stripePaymentIntent.api,
    autoBilling: loSubscription_ajv.autoBilling.api,
    boberdooId: loSubscription_ajv.boberdooId.api,
    boberdooBalance: loSubscription_ajv.boberdooBalance.api,
    bundleTitle: loSubscription_ajv.bundleTitle.api,
    cancelTime: loSubscription_ajv.cancelTime.api,
    companyId: loSubscription_ajv.companyId.api,
    createRequest: loSubscription_ajv.createRequest.api,
    createTime: loSubscription_ajv.createTime.api,
    currentStep: loSubscription_ajv.currentStep.api,
    dailyBudgetLimit: loSubscription_ajv.dailyBudgetLimit.api,
    dailyUnitLimit: loSubscription_ajv.dailyUnitLimit.api,
    deactivateTime: loSubscription_ajv.deactivateTime.api,
    deactivateReason: loSubscription_ajv.deactivateReason.api,
    finishTime: loSubscription_ajv.finishTime.api,
    inactive: loSubscription_ajv.inactive.api,
    price: loSubscription_ajv.price.api,
    priceSubscriptionItemId: loSubscription_ajv.priceSubscriptionItemId.api,
    productId: loSubscription_ajv.productId.api,
    transferPrice: loSubscription_ajv.transferPrice.api,
    transferPriceSubscriptionItemId: loSubscription_ajv.transferPriceSubscriptionItemId.api,
    updatedBy: loSubscription_ajv.updatedBy.api,
    updateRequest: loSubscription_ajv.updateRequest.api,
    updateTime: loSubscription_ajv.updateTime.api,
    activeLeadTransfer: loSubscription_ajv.activeLeadTransfer.api,
    agentState: loSubscription_ajv.agentState.api,
    callCenterService: loSubscription_ajv.callCenterService.api,
    creditStatus: loSubscription_ajv.creditStatus.api,
    scheduleDays: loSubscription_ajv.scheduleDays.api,
    scheduleFrom: loSubscription_ajv.scheduleFrom.api,
    scheduleTo: loSubscription_ajv.scheduleTo.api,
    timeZone: loSubscription_ajv.timeZone.api,
    primaryPhoneType: loSubscription_ajv.primaryPhoneType.api,
    primaryPhoneVerified: loSubscription_ajv.primaryPhoneVerified.api,
    secondaryPhoneType: loSubscription_ajv.secondaryPhoneType.api,
    secondaryPhone: loSubscription_ajv.secondaryPhone.api,
    secondaryPhoneVerified: loSubscription_ajv.secondaryPhoneVerified.api,
    alertList: loSubscription_ajv.alertList.api,
    addressCity: loSubscription_ajv.addressCity.api,
    addressCountry: loSubscription_ajv.addressCountry.api,
    addressState: loSubscription_ajv.addressState.api,
    addressStreet2: loSubscription_ajv.addressStreet2.api,
    addressStreet3: loSubscription_ajv.addressStreet3.api,
    preferredmeetingplaceCity: loSubscription_ajv.preferredmeetingplaceCity.api,
    preferredmeetingplaceState: loSubscription_ajv.preferredmeetingplaceState.api,
    preferredmeetingplaceStreet2: loSubscription_ajv.preferredmeetingplaceStreet2.api,
    preferredmeetingplaceStreet3: loSubscription_ajv.preferredmeetingplaceStreet3.api,
    preferredmeetingplaceZip: loSubscription_ajv.preferredmeetingplaceZip.api,
    preferredcommunicationscheduleDays: loSubscription_ajv.preferredcommunicationscheduleDays.api,
    preferredcommunicationscheduleTo: loSubscription_ajv.preferredcommunicationscheduleTo.api,
    infoPhone: loSubscription_ajv.infoPhone.api,
    infoWebsite: loSubscription_ajv.infoWebsite.api,
    transactionType: loSubscription_ajv.transactionType.api,
    loanRanges: loSubscription_ajv.loanRanges.api,
    vendors: loSubscription_ajv.vendors.api,
    totalTransferAmount: loSubscription_ajv.totalTransferAmount.api,
    totalLeadsTransfered: loSubscription_ajv.totalLeadsTransfered.api,
    totalRefunded: loSubscription_ajv.totalRefunded.api,
    weight: loSubscription_ajv.weight.api,
  },
  required: ['loanRanges', 'weight'],
  additionalProperties: false,
};

export default ajvInstance.compile(loSubscription_schema);
