import ajvInstance from '../ajv-instance';
import { contact_ajv } from '../mapper_ajv';


const contact_schema = {
  type: 'object',
  properties: {
    id: contact_ajv.id.api,
    accountId: contact_ajv.accountId.api,
    statusId: contact_ajv.statusId.api,
    addressId: contact_ajv.addressId.api,
    pictureUrl: contact_ajv.pictureUrl.api,
    nmlsId: contact_ajv.nmlsId.api,
    type: contact_ajv.type.api,
    firstName: contact_ajv.firstName.api,
    lastName: contact_ajv.lastName.api,
    personalEmail: contact_ajv.personalEmail.api,
    workEmail: contact_ajv.workEmail.api,
    mobilePhone: contact_ajv.mobilePhone.api,
    workPhone: contact_ajv.workPhone.api,
    extraMail: contact_ajv.extraMail.api,
    extraPhone: contact_ajv.extraPhone.api,
    jobTitle: contact_ajv.jobTitle.api,
    maritalStatus: contact_ajv.maritalStatus.api,
    fico: contact_ajv.fico.api,
    gender: contact_ajv.gender.api,
    dob: contact_ajv.dob.api,
    creationSource: contact_ajv.creationSource.api,
    ssn: contact_ajv.ssn.api,
    leadSourceType: contact_ajv.leadSourceType.api,
    leadSource: contact_ajv.leadSource.api,
    createdBy: contact_ajv.createdBy.api,
    createTime: contact_ajv.createTime.api,
    createRequest: contact_ajv.createRequest.api,
    updatedBy: contact_ajv.updatedBy.api,
    updateTime: contact_ajv.updateTime.api,
    updateRequest: contact_ajv.updateRequest.api,
    middleName: contact_ajv.middleName.api,
    autoIncrementId: contact_ajv.autoIncrementId.api,
    locale: contact_ajv.locale.api,
    monthlyIncome: contact_ajv.monthlyIncome.api,
    organizationId: contact_ajv.organizationId.api,
    origin: contact_ajv.origin.api,
    taygoSource: contact_ajv.taygoSource.api,
    timezone: contact_ajv.timezone.api,
    isDeleted: contact_ajv.isDeleted.api,
    isConverted: contact_ajv.isConverted.api,
    statusLifecycleId: contact_ajv.statusLifecycleId.api,
    homePhone: contact_ajv.homePhone.api,
  },
  required: [],
  additionalProperties: false,
};

export default ajvInstance.compile(contact_schema);
