import ajvInstance from '../ajv-instance';
import { loLeadRaw_ajv } from '../mapper_ajv';


const loLeadRaw_schema = {
  type: 'object',
  properties: {
    id: loLeadRaw_ajv.id.api,
    cost: loLeadRaw_ajv.cost.api,
    allowedTimesSold: loLeadRaw_ajv.allowedTimesSold.api,
    returnHashType: loLeadRaw_ajv.returnHashType.api,
    returnHashValueType: loLeadRaw_ajv.returnHashValueType.api,
    skipPartnerId: loLeadRaw_ajv.skipPartnerId.api,
    returnBestPrice: loLeadRaw_ajv.returnBestPrice.api,
    srcId: loLeadRaw_ajv.srcId.api,
    type: loLeadRaw_ajv.type.api,
    testLead: loLeadRaw_ajv.testLead.api,
    skipXsl: loLeadRaw_ajv.skipXsl.api,
    matchWithPartnerId: loLeadRaw_ajv.matchWithPartnerId.api,
    redirectUrl: loLeadRaw_ajv.redirectUrl.api,
    ipAddress: loLeadRaw_ajv.ipAddress.api,
    landingPage: loLeadRaw_ajv.landingPage.api,
    subId: loLeadRaw_ajv.subId.api,
    pubId: loLeadRaw_ajv.pubId.api,
    optout: loLeadRaw_ajv.optout.api,
    uniqueIdentifier: loLeadRaw_ajv.uniqueIdentifier.api,
    userAgent: loLeadRaw_ajv.userAgent.api,
    tcpaConsent: loLeadRaw_ajv.tcpaConsent.api,
    tcpaLanguage: loLeadRaw_ajv.tcpaLanguage.api,
    trustedFormUrl: loLeadRaw_ajv.trustedFormUrl.api,
    leadidToken: loLeadRaw_ajv.leadidToken.api,
    firstName: loLeadRaw_ajv.firstName.api,
    address: loLeadRaw_ajv.address.api,
    state: loLeadRaw_ajv.state.api,
    zip: loLeadRaw_ajv.zip.api,
    primaryPhone: loLeadRaw_ajv.primaryPhone.api,
    secondaryPhone: loLeadRaw_ajv.secondaryPhone.api,
    email: loLeadRaw_ajv.email.api,
    estimatedPurchasePrice: loLeadRaw_ajv.estimatedPurchasePrice.api,
    downPayment: loLeadRaw_ajv.downPayment.api,
    foundHome: loLeadRaw_ajv.foundHome.api,
    newPropertyZip: loLeadRaw_ajv.newPropertyZip.api,
    loanType: loLeadRaw_ajv.loanType.api,
    productType: loLeadRaw_ajv.productType.api,
    cashOutAmount: loLeadRaw_ajv.cashOutAmount.api,
    dob: loLeadRaw_ajv.dob.api,
    propertyUse: loLeadRaw_ajv.propertyUse.api,
    refiGoal: loLeadRaw_ajv.refiGoal.api,
    workingWithAnAgent: loLeadRaw_ajv.workingWithAnAgent.api,
    bankruptcyLast7Years: loLeadRaw_ajv.bankruptcyLast7Years.api,
    creditStatus: loLeadRaw_ajv.creditStatus.api,
    loanValue: loLeadRaw_ajv.loanValue.api,
    firstMortgageBalance: loLeadRaw_ajv.firstMortgageBalance.api,
    firstMortgageRate: loLeadRaw_ajv.firstMortgageRate.api,
    secondMortgage: loLeadRaw_ajv.secondMortgage.api,
    secondMortgageBalance: loLeadRaw_ajv.secondMortgageBalance.api,
    secondMortgageRate: loLeadRaw_ajv.secondMortgageRate.api,
    ltv: loLeadRaw_ajv.ltv.api,
    ssn: loLeadRaw_ajv.ssn.api,
    status: loLeadRaw_ajv.status.api,
    createRequest: loLeadRaw_ajv.createRequest.api,
    createTime: loLeadRaw_ajv.createTime.api,
    updateRequest: loLeadRaw_ajv.updateRequest.api,
    updatedBy: loLeadRaw_ajv.updatedBy.api,
    loLeadId: loLeadRaw_ajv.loLeadId.api,
    extraData: loLeadRaw_ajv.extraData.api,
    subscriptionId: loLeadRaw_ajv.subscriptionId.api,
    billingStatus: loLeadRaw_ajv.billingStatus.api,
  },
  required: [],
  additionalProperties: false,
};

export default ajvInstance.compile(loLeadRaw_schema);
