import ajvInstance from '../ajv-instance';
import { loSubscription_ajv } from '../mapper_ajv';


const loSubscription_schema = {
  type: 'object',
  properties: {
    id: loSubscription_ajv.id.api,
    stripeSubscription: loSubscription_ajv.stripeSubscription.api,
    stripeStatus: loSubscription_ajv.stripeStatus.api,
    autoBilling: loSubscription_ajv.autoBilling.api,
    boberdooBalance: loSubscription_ajv.boberdooBalance.api,
    cancelTime: loSubscription_ajv.cancelTime.api,
    companyId: loSubscription_ajv.companyId.api,
    createRequest: loSubscription_ajv.createRequest.api,
    currentStep: loSubscription_ajv.currentStep.api,
    dailyBudgetLimit: loSubscription_ajv.dailyBudgetLimit.api,
    dailyUnitLimit: loSubscription_ajv.dailyUnitLimit.api,
    deactivateReason: loSubscription_ajv.deactivateReason.api,
    inactive: loSubscription_ajv.inactive.api,
    price: loSubscription_ajv.price.api,
    productId: loSubscription_ajv.productId.api,
    transferPrice: loSubscription_ajv.transferPrice.api,
    updatedBy: loSubscription_ajv.updatedBy.api,
    updateTime: loSubscription_ajv.updateTime.api,
    activeLeadTransfer: loSubscription_ajv.activeLeadTransfer.api,
    callCenterService: loSubscription_ajv.callCenterService.api,
    creditStatus: loSubscription_ajv.creditStatus.api,
    scheduleFrom: loSubscription_ajv.scheduleFrom.api,
    scheduleTo: loSubscription_ajv.scheduleTo.api,
    primaryPhoneType: loSubscription_ajv.primaryPhoneType.api,
    primaryPhoneVerified: loSubscription_ajv.primaryPhoneVerified.api,
    secondaryPhoneType: loSubscription_ajv.secondaryPhoneType.api,
    secondaryPhoneVerified: loSubscription_ajv.secondaryPhoneVerified.api,
    addressCity: loSubscription_ajv.addressCity.api,
    addressState: loSubscription_ajv.addressState.api,
    addressStreet: loSubscription_ajv.addressStreet.api,
    addressStreet3: loSubscription_ajv.addressStreet3.api,
    preferredmeetingplaceCity: loSubscription_ajv.preferredmeetingplaceCity.api,
    preferredmeetingplaceCountry: loSubscription_ajv.preferredmeetingplaceCountry.api,
    preferredmeetingplaceStreet: loSubscription_ajv.preferredmeetingplaceStreet.api,
    preferredmeetingplaceStreet2: loSubscription_ajv.preferredmeetingplaceStreet2.api,
    preferredmeetingplaceZip: loSubscription_ajv.preferredmeetingplaceZip.api,
    county: loSubscription_ajv.county.api,
    preferredcommunicationscheduleFrom: loSubscription_ajv.preferredcommunicationscheduleFrom.api,
    infoEmail: loSubscription_ajv.infoEmail.api,
    infoName: loSubscription_ajv.infoName.api,
    leadType: loSubscription_ajv.leadType.api,
    loanRanges: loSubscription_ajv.loanRanges.api,
    vendors: loSubscription_ajv.vendors.api,
    totalMatchAmount: loSubscription_ajv.totalMatchAmount.api,
    totalLeadsMatched: loSubscription_ajv.totalLeadsMatched.api,
    totalCredited: loSubscription_ajv.totalCredited.api,
    leadCategory: loSubscription_ajv.leadCategory.api,
  },
  required: [],
  additionalProperties: false,
};

export default ajvInstance.compile(loSubscription_schema);
