import ajvInstance from '../ajv-instance';
import { loSubscription_ajv } from '../mapper_ajv';


const loSubscription_schema = {
  type: 'object',
  properties: {
    id: loSubscription_ajv.id.api,
    stripeSubscription: loSubscription_ajv.stripeSubscription.api,
    stripePaymentIntent: loSubscription_ajv.stripePaymentIntent.api,
    boberdooId: loSubscription_ajv.boberdooId.api,
    bundleTitle: loSubscription_ajv.bundleTitle.api,
    cancelTime: loSubscription_ajv.cancelTime.api,
    companyId: loSubscription_ajv.companyId.api,
    createRequest: loSubscription_ajv.createRequest.api,
    currentStep: loSubscription_ajv.currentStep.api,
    dailyBudgetLimit: loSubscription_ajv.dailyBudgetLimit.api,
    deactivateTime: loSubscription_ajv.deactivateTime.api,
    finishTime: loSubscription_ajv.finishTime.api,
    price: loSubscription_ajv.price.api,
    productId: loSubscription_ajv.productId.api,
    transferPriceSubscriptionItemId: loSubscription_ajv.transferPriceSubscriptionItemId.api,
    updateRequest: loSubscription_ajv.updateRequest.api,
    activeLeadTransfer: loSubscription_ajv.activeLeadTransfer.api,
    callCenterService: loSubscription_ajv.callCenterService.api,
    creditStatus: loSubscription_ajv.creditStatus.api,
    scheduleFrom: loSubscription_ajv.scheduleFrom.api,
    scheduleTo: loSubscription_ajv.scheduleTo.api,
    primaryPhoneType: loSubscription_ajv.primaryPhoneType.api,
    primaryPhone: loSubscription_ajv.primaryPhone.api,
    secondaryPhoneType: loSubscription_ajv.secondaryPhoneType.api,
    secondaryPhoneVerified: loSubscription_ajv.secondaryPhoneVerified.api,
    alertList: loSubscription_ajv.alertList.api,
    addressCountry: loSubscription_ajv.addressCountry.api,
    addressState: loSubscription_ajv.addressState.api,
    addressStreet2: loSubscription_ajv.addressStreet2.api,
    addressZip: loSubscription_ajv.addressZip.api,
    preferredmeetingplaceCity: loSubscription_ajv.preferredmeetingplaceCity.api,
    preferredmeetingplaceState: loSubscription_ajv.preferredmeetingplaceState.api,
    preferredmeetingplaceStreet2: loSubscription_ajv.preferredmeetingplaceStreet2.api,
    preferredmeetingplaceStreet3: loSubscription_ajv.preferredmeetingplaceStreet3.api,
    county: loSubscription_ajv.county.api,
    preferredcommunicationscheduleDays: loSubscription_ajv.preferredcommunicationscheduleDays.api,
    preferredcommunicationscheduleTo: loSubscription_ajv.preferredcommunicationscheduleTo.api,
    infoPhone: loSubscription_ajv.infoPhone.api,
    infoWebsite: loSubscription_ajv.infoWebsite.api,
    transactionType: loSubscription_ajv.transactionType.api,
    loanType: loSubscription_ajv.loanType.api,
    totalMatchAmount: loSubscription_ajv.totalMatchAmount.api,
    totalLeadsMatched: loSubscription_ajv.totalLeadsMatched.api,
    totalCredited: loSubscription_ajv.totalCredited.api,
    leadCategory: loSubscription_ajv.leadCategory.api,
  },
  required: [],
  additionalProperties: false,
};

export default ajvInstance.compile(loSubscription_schema);
